2019-11-25 16:45:14.609 - [Info] MITM Version: 1.26
2019-11-25 16:45:14.616 - [Info] Auto Access Enabled: true
2019-11-25 16:45:14.616 - [Debug] [Init] Auto Access Barrier: true
2019-11-25 16:45:14.643 - [Info] SSH man-in-the-middle server for 172.20.0.4 listening on 0.0.0.0:10103
2019-11-25 16:45:53.691 - [Debug] [Connection] Attacker connected: 180.76.249.74 | Client Identification: SSH-2.0-libssh-0.6.3
2019-11-25 16:46:04.471 - [Debug] [Connection] Attacker connected: 101.204.240.36 | Client Identification: SSH-2.0-libssh-0.6.3
2019-11-25 16:46:05.028 - [Debug] [Auth] Attacker 180.76.249.74 trying to authenticate with "password"
2019-11-25 16:46:05.029 - [Debug] [Auto Access] Attacker: 180.76.249.74, Threshold: 1, Attempts: 1
2019-11-25 16:46:05.029 - [Debug] [Auto Access] Compromising the honeypot
2019-11-25 16:46:05.030 - [Debug] [Auto Access] Adding the following credentials: "tappert:tappert"
2019-11-25 16:46:05.292 - [Debug] [Auth] Valid credentials - Password Authentication
2019-11-25 16:46:05.293 - [Debug] [LXC] Attempting to connect to the honeypot: 172.20.0.4
2019-11-25 16:46:05.339 - [Debug] [LXC-Auth] Attacker authenticated and is inside container
2019-11-25 16:46:06.279 - [Debug] [Connection] Attacker connected: 180.76.249.74 | Client Identification: SSH-2.0-libssh-0.6.3
2019-11-25 16:46:07.746 - [Debug] [Auth] Attacker 180.76.249.74 trying to authenticate with "password"
2019-11-25 16:46:07.747 - [Debug] [Auth] Attacker authentication error: Invalid credentials - User does not exist
2019-11-25 16:46:07.748 - [Debug] [Auth] Attacker: 180.76.249.74 has so far made 1 attempts. Remaining: 5 attempts
2019-11-25 16:46:08.237 - [Debug] [Connection] Attacker closed the connection
2019-11-25 16:46:08.709 - [Debug] [EXEC] Noninteractive mode attacker command: cat /proc/cpuinfo | grep name | wc -l
2019-11-25 17:02:56.081 - [Debug] [Connection] Client error on ssh server
2019-11-25 17:02:56.082 - [Debug] [Connection] Attacker closed the connection
