2019-11-13 02:44:34.809 - [Info] MITM Version: 1.26
2019-11-13 02:44:34.819 - [Info] Auto Access Enabled: true
2019-11-13 02:44:34.819 - [Debug] [Init] Auto Access Barrier: true
2019-11-13 02:44:34.879 - [Info] SSH man-in-the-middle server for 172.20.0.5 listening on 0.0.0.0:10104
2019-11-13 03:12:13.580 - [Debug] [Connection] Attacker connected: 159.203.69.48 | Client Identification: SSH-2.0-libssh-0.6.3
2019-11-13 03:12:31.077 - [Debug] [Connection] Attacker closed the connection
2019-11-13 03:20:27.501 - [Debug] [Connection] Attacker connected: 211.157.189.54 | Client Identification: SSH-2.0-libssh-0.6.3
2019-11-13 03:20:30.925 - [Debug] [Auth] Attacker 211.157.189.54 trying to authenticate with "password"
2019-11-13 03:20:30.927 - [Debug] [Auto Access] Attacker: 211.157.189.54, Threshold: 1, Attempts: 1
2019-11-13 03:20:30.927 - [Debug] [Auto Access] Compromising the honeypot
2019-11-13 03:20:30.927 - [Debug] [Auto Access] Adding the following credentials: "shiaomin:shiaomin"
2019-11-13 03:20:31.300 - [Debug] [Auth] Valid credentials - Password Authentication
2019-11-13 03:20:31.300 - [Debug] [LXC] Attempting to connect to the honeypot: 172.20.0.5
2019-11-13 03:20:31.376 - [Debug] [LXC-Auth] Attacker authenticated and is inside container
2019-11-13 03:20:34.501 - [Debug] [Connection] Attacker connected: 211.157.189.54 | Client Identification: SSH-2.0-libssh-0.6.3
2019-11-13 03:20:38.257 - [Debug] [Auth] Attacker 211.157.189.54 trying to authenticate with "password"
2019-11-13 03:20:38.258 - [Debug] [Auth] Attacker authentication error: Invalid credentials - User does not exist
2019-11-13 03:20:38.260 - [Debug] [Auth] Attacker: 211.157.189.54 has so far made 1 attempts. Remaining: 5 attempts
2019-11-13 03:20:38.813 - [Debug] [Connection] Attacker closed the connection
2019-11-13 03:20:39.861 - [Debug] [EXEC] Noninteractive mode attacker command: cat /proc/cpuinfo | grep name | wc -l
