2019-11-17 16:25:58.350 - [Info] MITM Version: 1.26
2019-11-17 16:25:58.356 - [Info] Auto Access Enabled: true
2019-11-17 16:25:58.356 - [Debug] [Init] Auto Access Barrier: true
2019-11-17 16:25:58.378 - [Info] SSH man-in-the-middle server for 172.20.0.6 listening on 0.0.0.0:10105
2019-11-17 16:32:29.079 - [Debug] [Connection] Attacker connected: 167.172.254.47 | Client Identification: SSH-2.0-libssh-0.1
2019-11-17 16:32:29.102 - [Debug] [Connection] Attacker closed the connection
2019-11-17 17:04:01.336 - [Debug] [Connection] Attacker connected: 195.58.123.109 | Client Identification: SSH-2.0-libssh-0.6.3
2019-11-17 17:04:02.215 - [Debug] [Auth] Attacker 195.58.123.109 trying to authenticate with "password"
2019-11-17 17:04:02.216 - [Debug] [Auto Access] Attacker: 195.58.123.109, Threshold: 1, Attempts: 1
2019-11-17 17:04:02.217 - [Debug] [Auto Access] Compromising the honeypot
2019-11-17 17:04:02.217 - [Debug] [Auto Access] Adding the following credentials: "root:@WSX@WSX@WSX"
2019-11-17 17:04:02.382 - [Debug] [Auth] Valid credentials - Password Authentication
2019-11-17 17:04:02.382 - [Debug] [LXC] Attempting to connect to the honeypot: 172.20.0.6
2019-11-17 17:04:02.447 - [Debug] [LXC-Auth] Attacker authenticated and is inside container
2019-11-17 17:04:03.002 - [Debug] [Connection] Attacker connected: 195.58.123.109 | Client Identification: SSH-2.0-libssh-0.6.3
2019-11-17 17:04:03.830 - [Debug] [Auth] Attacker 195.58.123.109 trying to authenticate with "password"
2019-11-17 17:04:03.830 - [Debug] [Auth] Attacker authentication error: Invalid credentials - User does not exist
2019-11-17 17:04:03.831 - [Debug] [Auth] Attacker: 195.58.123.109 has so far made 1 attempts. Remaining: 5 attempts
2019-11-17 17:04:04.122 - [Debug] [Connection] Attacker closed the connection
2019-11-17 17:04:04.383 - [Debug] [EXEC] Noninteractive mode attacker command: cat /proc/cpuinfo | grep name | wc -l
