2019-11-19 18:49:44.346 - [Info] MITM Version: 1.26
2019-11-19 18:49:44.353 - [Info] Auto Access Enabled: true
2019-11-19 18:49:44.353 - [Debug] [Init] Auto Access Barrier: true
2019-11-19 18:49:44.743 - [Info] SSH man-in-the-middle server for 172.20.0.4 listening on 0.0.0.0:10103
2019-11-19 19:08:42.718 - [Debug] [Connection] Attacker connected: 178.128.97.154 | Client Identification: SSH-2.0-paramiko_2.6.0
2019-11-19 20:01:59.768 - [Debug] [Connection] Attacker connected: 45.40.198.41 | Client Identification: SSH-2.0-libssh-0.6.3
2019-11-19 20:02:01.554 - [Debug] [Auth] Attacker 45.40.198.41 trying to authenticate with "password"
2019-11-19 20:02:01.556 - [Debug] [Auto Access] Attacker: 45.40.198.41, Threshold: 1, Attempts: 1
2019-11-19 20:02:01.556 - [Debug] [Auto Access] Compromising the honeypot
2019-11-19 20:02:01.556 - [Debug] [Auto Access] Adding the following credentials: "root:h4ck"
2019-11-19 20:02:01.699 - [Debug] [Auth] Valid credentials - Password Authentication
2019-11-19 20:02:01.699 - [Debug] [LXC] Attempting to connect to the honeypot: 172.20.0.4
2019-11-19 20:02:01.739 - [Debug] [LXC-Auth] Attacker authenticated and is inside container
2019-11-19 20:02:02.877 - [Debug] [Connection] Attacker connected: 45.40.198.41 | Client Identification: SSH-2.0-libssh-0.6.3
2019-11-19 20:02:04.587 - [Debug] [Auth] Attacker 45.40.198.41 trying to authenticate with "password"
2019-11-19 20:02:04.588 - [Debug] [Auth] Attacker authentication error: Invalid credentials - User does not exist
2019-11-19 20:02:04.590 - [Debug] [Auth] Attacker: 45.40.198.41 has so far made 1 attempts. Remaining: 5 attempts
2019-11-19 20:02:05.171 - [Debug] [Connection] Attacker closed the connection
2019-11-19 20:02:05.751 - [Debug] [EXEC] Noninteractive mode attacker command: cat /proc/cpuinfo | grep name | wc -l
